name: Deploy

concurrency:
  group: deploy
  cancel-in-progress: false

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    steps:
      - name: Check if directory and git repository exist
        run: test -d /opt/practice-field-scheduler/.git

      - name: Pull latest changes
        working-directory: /opt/practice-field-scheduler
        run: git pull origin master

      - name: Install dependencies
        working-directory: /opt/practice-field-scheduler
        run: npm ci

      - name: Build application
        working-directory: /opt/practice-field-scheduler
        run: npm run build

      - name: Restart service
        run: sudo systemctl restart practice-field-scheduler.service
